### ISSUE TITLE
Host the website somewhere so it can be accessed from the internet

### ISSUE THREAD

**Issue by durw4rd** [stasel/c50-browsers-project#25]
As a user, I want to be able to access the Quiz app without having to download the application code and run it locally.

Plus points if you also figure out how to set up an automatic redeploy after a PR is merged but no worries if that part is missing.

**Comment by liya-oz** [comment]
As our very first and very important user, we are pleased to invite you, @durw4rd, to the webpage of the project: [C50 Browsers Project](https://stasel.github.io/c50-browsers-project).
